version: '3'

includes:
  test:
    taskfile: ./test/Taskfile.yml
    dir: ./test

vars:
  IMG: logiciq/pvc-chonker:latest
  CLUSTER_NAME: pvc-chonker-test

tasks:
  default:
    desc: Build the project
    cmds:
      - task: build

  help:
    desc: Display available tasks
    cmds:
      - task --list

  check:
    desc: Run all checks (fmt, vet, unit tests)
    deps: [fmt, vet]
    cmds:
      - task: test-unit

  fmt:
    desc: Run go fmt against code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet against code
    cmds:
      - go vet ./...

  test:
    desc: Run all tests
    deps: [fmt, vet]
    cmds:
      - go test ./... -coverprofile cover.out

  test-unit:
    desc: Run unit tests
    cmds:
      - go test -v ./pkg/... ./internal/...

  test-coverage:
    desc: Run tests with coverage report
    cmds:
      - go test -v -coverprofile=coverage.out ./pkg/... ./internal/...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  test-clean:
    desc: Clean test artifacts
    cmds:
      - rm -f coverage.out coverage.html cover.out

  test-integration:
    desc: Run integration tests
    dir: test/integration
    cmds:
      - task: run

  e2e-setup:
    desc: Setup Kind cluster for E2E testing
    dir: test/e2e
    cmds:
      - task: setup

  e2e-run:
    desc: Run E2E tests
    dir: test/e2e
    cmds:
      - task: run

  e2e-cleanup:
    desc: Cleanup Kind cluster
    dir: test/e2e
    cmds:
      - task: cleanup

  build:
    desc: Build manager binary
    deps: [fmt, vet]
    cmds:
      - go build -o bin/manager cmd/main.go

  run:
    desc: Run controller from your host
    deps: [fmt, vet]
    cmds:
      - go run ./cmd/main.go

  docker-build:
    desc: Build docker image with the manager
    deps: [build]
    cmds:
      - docker build -t {{.IMG}} .

  docker-push:
    desc: Push docker image with the manager
    cmds:
      - docker login
      - docker push {{.IMG}}

  deploy:
    desc: Deploy controller to the K8s cluster specified in ~/.kube/config
    cmds:
      - kubectl apply -f config/

  undeploy:
    desc: Undeploy controller from the K8s cluster specified in ~/.kube/config
    cmds:
      - kubectl delete -f config/