version: '3'

vars:
  IMG: logiciq/pvc-chonker:latest
  CLUSTER_NAME: chonker-e2e

tasks:
  # Main development tasks
  default:
    desc: Build the project
    cmds:
      - task: go:build

  dev:setup:
    desc: Setup development environment
    cmds:
      - task: go:manifests
      - task: go:generate
      - task: go:fmt

  run:local:
    desc: Run controller locally
    deps: [go:fmt, go:generate, go:manifests]
    cmds:
      - go run ./cmd/main.go

  # Go tasks
  go:build:
    desc: Build manager binary
    deps: [go:fmt, go:generate, go:manifests]
    cmds:
      - |
        VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "dev")
        GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
        go build -ldflags="-X main.version=${VERSION} -X main.gitHash=${GIT_HASH}" -o bin/manager cmd/main.go

  go:fmt:
    desc: Format and vet Go code
    cmds:
      - go fmt ./...
      - go vet ./...

  go:generate:
    desc: Generate code containing DeepCopy methods
    cmds:
      - controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."

  go:manifests:
    desc: Generate CRD manifests
    cmds:
      - controller-gen crd:headerFile="hack/boilerplate.go.txt" paths="./..." output:crd:artifacts:config=config/crd/bases
      - controller-gen rbac:roleName=manager-role paths="./..." output:rbac:artifacts:config=config/rbac

  go:test:
    desc: Run all unit tests with coverage
    deps: [go:fmt]
    cmds:
      - go test -v -race -coverprofile=coverage.out ./pkg/... ./internal/...
      - go tool cover -func=coverage.out
      - go tool cover -html=coverage.out -o coverage.html

  go:test:unit:
    desc: Run unit tests only
    cmds:
      - go test -v ./pkg/... ./internal/...

  # Docker tasks
  docker:build:
    desc: Build docker image
    deps: [go:build]
    cmds:
      - docker build -t {{.IMG}} .

  docker:push:
    desc: Push docker image
    cmds:
      - docker push {{.IMG}}

  # Kubernetes tasks
  k8s:install:
    desc: Install CRDs into the cluster
    cmds:
      - task: go:manifests
      - kubectl apply -f config/crd/bases/

  k8s:uninstall:
    desc: Uninstall CRDs from the cluster
    cmds:
      - kubectl delete -f config/crd/bases/ --ignore-not-found=true

  k8s:deploy:
    desc: Deploy to current cluster
    cmds:
      - kubectl apply -f config/

  k8s:undeploy:
    desc: Remove from current cluster
    cmds:
      - kubectl delete -f config/

  # E2E tasks
  e2e:run:
    desc: Run complete e2e test suite
    cmds:
      - echo "Running pre-test cleanup..."
      - kubectl delete pvc --all -n pvc-chonker-system --ignore-not-found=true --timeout=60s || echo "PVC cleanup failed but continuing..."
      - kubectl delete pvcgroups --all -n pvc-chonker-system --ignore-not-found=true --timeout=30s || echo "PVCGroup cleanup failed but continuing..."
      - kubectl delete pvcpolicies --all -n pvc-chonker-system --ignore-not-found=true --timeout=30s || echo "PVCPolicy cleanup failed but continuing..."
      - kubectl delete pods --all -n pvc-chonker-system --ignore-not-found=true --timeout=30s || echo "Pod cleanup failed but continuing..."
      - kubectl delete ns pvc-chonker-system --ignore-not-found=true --timeout=120s || echo "Namespace cleanup failed but continuing..."
      - kubectl delete ns -l "name~=webhook.*test" --ignore-not-found=true --timeout=120s || echo "Test namespace cleanup failed but continuing..."
      - echo "Starting e2e tests..."
      - cd e2e && task e2e

  e2e:test:
    desc: Run e2e tests only (assumes cluster exists)
    cmds:
      - cd e2e && task test

  e2e:setup:
    desc: Setup e2e environment only
    cmds:
      - cd e2e && task setup

  e2e:deploy:
    desc: Deploy operator to e2e cluster
    cmds:
      - cd e2e && task deploy

  e2e:cleanup:
    desc: Cleanup e2e environment
    cmds:
      - cd e2e && task cleanup

  # Utility tasks
  clean:
    desc: Clean artifacts
    cmds:
      - rm -f coverage.out coverage.html cover.out bin/manager

