version: '3'

includes:
  test:e2e:
    taskfile: ./e2e/Taskfile.yml
    dir: ./e2e

vars:
  IMG: logiciq/pvc-chonker:latest
  CLUSTER_NAME: chonker-e2e

tasks:
  # Main development tasks
  default:
    desc: Build the project
    cmds:
      - task: go:build

  dev:
    desc: Run controller locally
    deps: [go:fmt, go:vet]
    cmds:
      - go run ./cmd/main.go

  # Go tasks
  go:build:
    desc: Build manager binary
    deps: [go:fmt, go:vet]
    cmds:
      - go build -o bin/manager cmd/main.go

  go:fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  go:vet:
    desc: Vet code
    cmds:
      - go vet ./...

  go:check:
    desc: Run all checks
    deps: [go:fmt, go:vet]
    cmds:
      - task: test:unit

  go:clean:
    desc: Clean artifacts
    cmds:
      - rm -f coverage.out coverage.html cover.out bin/manager

  # Testing tasks
  test:
    desc: Run all tests
    deps: [go:fmt, go:vet]
    cmds:
      - go test ./... -coverprofile cover.out

  test:unit:
    desc: Run unit tests
    cmds:
      - go test -v ./pkg/... ./internal/...

  test:cov:
    desc: Run tests with coverage report
    cmds:
      - go test -v -coverprofile=coverage.out ./pkg/... ./internal/...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report generated at coverage.html"

  test:integration:
    desc: Run integration tests with kind
    cmds:
      - task: test:e2e:run

  test:deploy:
    desc: Redeploy operator during development
    cmds:
      - task: test:e2e:deploy

  test:cleanup:
    desc: Clean up test environment
    cmds:
      - task: test:e2e:cleanup

  test:csi:
    desc: Test with real CSI VolumeStats
    cmds:
      - task: test:e2e:test-csi

  # Docker tasks
  docker:
    desc: Build docker image
    cmds:
      - task: docker:build

  docker:build:
    desc: Build docker image
    deps: [go:build]
    cmds:
      - docker build -t {{.IMG}} .

  docker:push:
    desc: Push docker image
    cmds:
      - docker push {{.IMG}}

  # Deployment tasks
  deploy:
    desc: Deploy to current cluster
    cmds:
      - kubectl apply -f config/

  undeploy:
    desc: Remove from current cluster
    cmds:
      - kubectl delete -f config/

