version: '3'

vars:
  IMG: logiciq/pvc-chonker:latest
  CLUSTER_NAME: pvc-chonker

tasks:
  install-kind:
    desc: Install kind if not present
    status:
      - which kind
    cmds:
      - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
      - chmod +x ./kind
      - sudo mv ./kind /usr/local/bin/kind

  create-cluster:
    desc: Create kind cluster
    deps: [install-kind]
    status:
      - kind get clusters | grep {{.CLUSTER_NAME}}
    cmds:
      - mkdir -p /tmp/hostpathcsi
      - kind create cluster --name {{.CLUSTER_NAME}} --config fixtures/kind-config.yaml
      - kubectl wait --for=condition=Ready nodes --all --timeout=60s

  setup:
    desc: Setup test environment with mock metrics
    deps: [create-cluster]
    cmds:
      - kubectl apply -f fixtures/storage-class.yaml
      - kubectl apply -f fixtures/mock-kubelet-metrics.yaml
      - kubectl wait --for=condition=Ready pod -l app=mock-kubelet-metrics -n kube-system --timeout=60s



  deploy:
    desc: Deploy operator to cluster with mock kubelet
    deps: [setup]
    cmds:
      - cd .. && task docker:build
      - kind load docker-image {{.IMG}} --name {{.CLUSTER_NAME}}
      - kubectl apply -R -f ../config/
      - |
        kubectl patch deployment controller-manager -n pvc-chonker-system -p '{
          "spec": {
            "template": {
              "spec": {
                "containers": [{
                  "name": "manager",
                  "imagePullPolicy": "Never",
                  "env": [{
                    "name": "PVC_CHONKER_KUBELET_URL",
                    "value": "http://mock-kubelet-metrics.kube-system.svc.cluster.local:10255"
                  }]
                }]
              }
            }
          }
        }'
      - kubectl rollout restart deployment controller-manager -n pvc-chonker-system
      - sleep 12
      - kubectl wait --for=condition=Ready pod -l control-plane=controller-manager -n pvc-chonker-system --timeout=120s
      - kubectl apply -f fixtures/test-pvc.yaml
      - kubectl delete pod test-pod --ignore-not-found=true
      - kubectl apply -f fixtures/test-pod.yaml

  run:
    desc: Run full E2E test
    cmds:
      - task: deploy
      - task: test

  test:
    desc: Execute automated E2E tests
    cmds:
      - go mod tidy
      - go test -v ./... -timeout=5m

  status:
    desc: Show comprehensive operator status and activity
    cmds:
      - echo "=== Operator Status ==="
      - kubectl get pods -n pvc-chonker-system
      - echo ""
      - echo "=== PVC Status ==="
      - kubectl get pvc test-pvc
      - echo ""
      - echo "=== Test Pod Status ==="
      - kubectl get pod test-pod
      - echo ""
      - echo "=== Current Disk Usage ==="
      - kubectl exec test-pod -- df -h /data 2>/dev/null || echo "Pod not ready"
      - echo ""
      - echo "=== Recent Operator Logs ==="
      - kubectl logs deployment/controller-manager -n pvc-chonker-system --tail=20 --since=5m
      - echo ""
      - echo "=== Mock Kubelet Metrics ==="
      - kubectl exec -n kube-system -l app=mock-kubelet-metrics -- curl -s localhost:10255/metrics | grep kubelet_volume_stats


  cleanup:
    desc: Clean up test environment
    cmds:
      - kind delete cluster --name {{.CLUSTER_NAME}}