version: '3'

vars:
  IMG: logiciq/pvc-chonker:latest
  CLUSTER_NAME: pvc-chonker

tasks:
  e2e:
    desc: Run complete E2E test suite (single command)
    cmds:
      - echo "Starting complete E2E test suite with Minikube + CSI HostPath"
      - task: create-cluster
      - task: setup
      - task: deploy
      - task: test
      - echo "E2E test suite completed successfully"

  create-cluster:
    desc: Create minikube cluster with CSI HostPath driver
    status:
      - minikube status -p {{.CLUSTER_NAME}} | grep Running
    cmds:
      - echo "Creating minikube cluster with CSI HostPath driver and admission controllers..."
      - MINIKUBE_IN_STYLE=false minikube start -p {{.CLUSTER_NAME}} --cpus=2 --memory=4096 --disk-size=20g --driver=docker --cache-images=true --embed-certs=true --addons=csi-hostpath-driver --kubernetes-version=v1.28.3 --extra-config=apiserver.enable-admission-plugins=MutatingAdmissionWebhook,ValidatingAdmissionWebhook
      - kubectl wait --for=condition=Ready nodes --all --timeout=120s
      - echo "Cluster created with CSI driver enabled"

  setup:
    desc: Setup test environment with CSI HostPath storage
    deps: [create-cluster]
    cmds:
      - echo "Setting up test environment..."
      - kubectl apply -f fixtures/storage-class.yaml
      - kubectl wait --for=condition=Ready pod -l addonmanager.kubernetes.io/mode=Reconcile -n kube-system --timeout=120s
      - echo "CSI HostPath driver ready"


  deploy:
    desc: Deploy operator to cluster
    deps: [setup]
    cmds:
      - task: _deploy-operator
        vars:
          WATCH_INTERVAL: "15s"

  test:
    desc: Execute automated E2E tests
    cmds:
      - echo "Running E2E tests..."
      - go mod tidy
      - go test -v ./... -timeout=10m
      - echo "All E2E tests passed"

  test-webhook:
    desc: Test webhook configuration
    deps: [deploy]
    cmds:
      - echo "Testing webhook configuration..."
      - kubectl get secret pvc-chonker-webhook-server-cert -n pvc-chonker-system
      - kubectl get mutatingadmissionwebhook pvc-chonker-mutating-webhook-configuration
      - echo "Webhook configuration test passed"

  deploy-webhook:
    desc: Deploy operator with webhook enabled
    deps: [setup]
    cmds:
      - task: _deploy-operator
        vars:
          WATCH_INTERVAL: "5s"

  _deploy-operator:
    internal: true
    cmds:
      - echo "Building and deploying operator..."
      - cd .. && task docker:build
      - minikube image load {{.IMG}} -p {{.CLUSTER_NAME}}
      - kubectl apply -R -f ../config/
      - echo "Applying webhook configuration..."
      - kubectl apply -f ../config/webhook/
      - sleep 5
      - |
        kubectl patch deployment controller-manager -n pvc-chonker-system -p '{
          "spec": {
            "template": {
              "spec": {
                "containers": [{
                  "name": "manager",
                  "imagePullPolicy": "Never",
                  "env": [{
                    "name": "PVC_CHONKER_ENABLE_WEBHOOK",
                    "value": "true"
                  }, {
                    "name": "PVC_CHONKER_WATCH_INTERVAL",
                    "value": "{{.WATCH_INTERVAL}}"
                  }]
                }]
              }
            }
          }
        }'
      - kubectl rollout restart deployment controller-manager -n pvc-chonker-system
      - sleep 10
      - kubectl get pods -n pvc-chonker-system
      - kubectl wait --for=condition=Available deployment/controller-manager -n pvc-chonker-system --timeout=180s
      - echo "Waiting for webhook server to be ready..."
      - sleep 10
      - kubectl apply -f fixtures/test-pvc.yaml -n pvc-chonker-system
      - kubectl delete pod test-pod -n pvc-chonker-system --ignore-not-found=true
      - kubectl apply -f fixtures/test-pod.yaml -n pvc-chonker-system
      - kubectl wait --for=condition=Ready pod test-pod -n pvc-chonker-system --timeout=60s
      - echo "Operator deployed and test workload ready"

  verify-metrics:
    desc: Verify kubelet volume metrics are available
    deps: [setup]
    cmds:
      - echo "Verifying kubelet volume metrics..."
      - kubectl apply -f fixtures/test-pvc.yaml -n pvc-chonker-system
      - kubectl delete pod test-pod -n pvc-chonker-system --ignore-not-found=true
      - kubectl apply -f fixtures/test-pod.yaml -n pvc-chonker-system
      - kubectl wait --for=condition=Ready pod test-pod -n pvc-chonker-system --timeout=60s
      - sleep 10
      - kubectl get --raw /api/v1/nodes/{{.CLUSTER_NAME}}/proxy/metrics | grep kubelet_volume_stats
      - echo "Volume metrics verified"

  status:
    desc: Show comprehensive operator status and activity
    cmds:
      - echo "=== Cluster Status ==="
      - kubectl get nodes
      - echo ""
      - echo "=== CSI Driver Status ==="
      - kubectl get pods -n kube-system | grep csi
      - echo ""
      - echo "=== Operator Status ==="
      - kubectl get pods -n pvc-chonker-system
      - echo ""
      - echo "=== PVC Status ==="
      - kubectl get pvc -n pvc-chonker-system
      - echo ""
      - echo "=== Test Pod Status ==="
      - kubectl get pod test-pod -n pvc-chonker-system 2>/dev/null || echo "Test pod not found"
      - echo ""
      - echo "=== Current Disk Usage ==="
      - kubectl exec test-pod -n pvc-chonker-system -- df -h /data 2>/dev/null || echo "Pod not ready"
      - echo ""
      - echo "=== Recent Operator Logs ==="
      - kubectl logs deployment/controller-manager -n pvc-chonker-system --tail=20 --since=5m 2>/dev/null || echo "Operator not ready"
      - echo ""
      - echo "=== Volume Metrics Sample ==="
      - kubectl get --raw /api/v1/nodes/{{.CLUSTER_NAME}}/proxy/metrics 2>/dev/null | grep kubelet_volume_stats | head -5 || echo "Metrics not available"

  cleanup:
    desc: Clean up test environment
    cmds:
      - echo "Cleaning up test environment..."
      - MINIKUBE_IN_STYLE=false minikube delete -p {{.CLUSTER_NAME}}
      - echo "Cleanup completed"